### ISSUE TITLE
SCP03 impl not using the third byte of the Init_Update response key info

### ISSUE THREAD

**Issue by JakeL2BT** [kaoh/homebrew-globalplatform#1]
SCP03 impl not using the third byte of the Init_Update response key info (010370).
The Get_Data responses indicate 
66 : Gp, GP v2.2.1, GP SCP03 i=10, JavaCard v3
67 : SCP03 i=00, 10, 20, 30, 60, 70 with AES-(128, 196, 256)
This was performed on a Ubuntu 20.04 host.
get_data -identifier 9F7F
Command --> 80CA9F7F00
Wrapped command --> 80CA9F7F00
Response <-- 9F7F2A00050045D001718901010604002D0016990E0000000000000000000000000000000000000000000000009000
9F7F2A00050045D001718901010604002D0016990E000000000000000000000000000000000000000000000000
get_data -identifier 66
Command --> 80CA006600
Wrapped command --> 80CA006600
Response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E0103
send_apdu_nostop -APDU 80CA006700
Command --> 80CA006700
Wrapped command --> 80CA006700
Response <-- 6735A00E8001038106001020306070820107A007800102810215558103FF9E0082031E160083010284018F8502FF028602FF028702FF029000
send_APDU() returns 0x80209000 (9000: Success. No error.)
send_apdu_nostop -APDU 80CA00E000
Command --> 80CA00E000
Wrapped command --> 80CA00E000
Response <-- E012C00401018810C00402018810C004030188109000
send_APDU() returns 0x80209000 (9000: Success. No error.)
send_apdu_nostop -APDU 80CA00CF00
Command --> 80CA00CF00
Wrapped command --> 80CA00CF00
Response <-- CF0A00000604002D0016990E9000
send_APDU() returns 0x80209000 (9000: Success. No error.)
send_apdu_nostop -APDU 80CA00C100
Command --> 80CA00C100
Wrapped command --> 80CA00C100
Response <-- C1030000C29000
send_APDU() returns 0x80209000 (9000: Success. No error.)
send_apdu_nostop -APDU 80CA00C200
Command --> 80CA00C200
Wrapped command --> 80CA00C200
Response <-- C20200009000
send_APDU() returns 0x80209000 (9000: Success. No error.)
select
Command --> 00A4040000
Wrapped command --> 00A4040000
Response <-- 6F108408A000000003000000A5049F6501FF9000
get_key_information_templates
Unknown command get_key_information_templates
get_extended_card_resources_information
Unknown command get_extended_card_resources_information
get_secure_channel_protocol_details
Unknown command get_secure_channel_protocol_details
get_card_recognition_data
Unknown command get_card_recognition_data
open_sc -security 3 -keyind 0 -keyver 0 -mac_key 404142434445464748494a4b4c4d4e4f -enc_key 404142434445464748494a4b4c4d4e4f
Command --> 80CA006600
Wrapped command --> 80CA006600
Response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
Command --> 8050000008B371C03D39EFF3FE00
Wrapped command --> 8050000008B371C03D39EFF3FE00
Response <-- 00000604002D0016990E010370359B887EEECBFA73E6B409E81BE701E70000C29000
mutual_authentication() returns 0x8030F00B (The response of the command was invalid.)

**Comment by kaoh** [comment]
Which version are you using? Because I'm wondering why the commands `get_key_information_templates` are not supported.

Have you used `brew` for installing it? If so, please execute:

~~~
brew remove globalplatform
brew untap kaoh/globalplatform
brew install kaoh/globalplatform/globalplatform
~~~

This should install version 2.

I have successfully used this script against a SCP03 card in MacOS:
~~~
mode_211
enable_trace
enable_timer
establish_context
card_connect -protocol 1
select -AID A000000151000000
get_key_information_templates -noStop
get_extended_card_resources_information -noStop
get_secure_channel_protocol_details -noStop
open_sc -security 1 -keyind 0 -keyver 0 -mac_key 404142434445464748494a4b4c4d4e4f -enc_key 404142434445464748494a4b4c4d4e4f
card_disconnect
release_context
~~~

**Comment by JakeL2BT** [comment]
I performed the brew steps.
Then:
select 
Command --> 00A4040000
Wrapped command --> 00A4040000
Response <-- 6F108408A000000003000000A5049F6501FF9000
command time: 29 ms
get_key_information_templates -noStop
Unknown command get_key_information_templates
get_extended_card_resources_information -noStop
Unknown command get_extended_card_resources_information
get_secure_channel_protocol_details -noStop
Unknown command get_secure_channel_protocol_details
open_sc -security 3 -keyind 0 -keyver 0 -mac_key 404142434445464748494a4b4c4d4e4f -enc_key 404142434445464748494a4b4c4d4e4f
Command --> 80CA006600
Wrapped command --> 80CA006600
Response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
Command --> 80500000085894CCDC7C6F198500
Wrapped command --> 80500000085894CCDC7C6F198500
Response <-- 00000604002D0016990E010370A396E8AABD9995CEEFA66B8B2B50B76E0000C89000
mutual_authentication() returns 0x8030F00B (The response of the command was invalid.)

**Comment by kaoh** [comment]
The strange thing is, I still see messages like "Unknown command get_key_information_templates" which should not happen and might indicate that a different version is running. Are you running MacOS or Linux? Can you also please check if you have several versions of the executable file `gpshell` installed, i.e. do a full system file search? I have the assumption that somehow a different version is on the PATH and the Homebrew version from `/usr/local/` is not used.

**Comment by JakeL2BT** [comment]
I running on a Ubuntu 20.02. I'm sure I have several install but will search and try to correct it.

66 - 64886FC6B040310 : SCP03 impl 10
Response <-- 6735A00E 
800103
8106001020306070
820107A007800102810215558103FF9E0082031E160083010284018F8502FF028602FF028702FF029000
Command --> 80500000085894CCDC7C6F198500
Wrapped command --> 80500000085894CCDC7C6F198500
Response <-- 00000604002D0016990E 010370 A396E8AABD9995CEEFA66B8B2B50B76E0000C89000

**Comment by JakeL2BT** [comment]
So I corrected the path issue. This is the log of the following run.

~~~
select 
Command --> 00A4040000
Wrapped command --> 00A4040000
Response <-- 6F108408A000000003000000A5049F6501FF9000
Unwrapped response <-- 6F108408A000000003000000A5049F6501FF9000
command time: 30 ms
get_key_information_templates -noStop
Command --> 80CA00E000
Wrapped command --> 80CA00E000
Response <-- E012C00401018810C00402018810C004030188109000
Unwrapped response <-- E012C00401018810C00402018810C004030188109000
ID  | Version | Type   | Length | Usage | Access 
--  | --      | --     | --     | --    | --     
1   | 1       | 88     | 16     | 00    | 00     
--  | --      | --     | --     | --    | --     
2   | 1       | 88     | 16     | 00    | 00     
--  | --      | --     | --     | --    | --     
3   | 1       | 88     | 16     | 00    | 00     
command time: 19 ms
get_extended_card_resources_information -noStop
Command --> 80CAFF2100
Wrapped command --> 80CAFF2100
Response <-- 6A88
Unwrapped response <-- 6A88
get_extended_card_resources_information() returns 0x80206A88 (6A88: Referenced data not found.)
get_secure_channel_protocol_details -noStop
Command --> 80CA006600
Wrapped command --> 80CA006600
Response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
Unwrapped response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
SCP: 0x03
SCP Impl: 0x10
command time: 52 ms
open_sc -security 3 -keyind 0 -keyver 0 -mac_key 404142434445464748494a4b4c4d4e4f -enc_key 404142434445464748494a4b4c4d4e4f
Command --> 8050000008934D3B5A8E94AF6900
Wrapped command --> 8050000008934D3B5A8E94AF6900
Response <-- 00000604002D0016990E0103707D25077AA35F83232232C32B076554D80000CD9000
Unwrapped response <-- 00000604002D0016990E0103707D25077AA35F83232232C32B076554D80000CD9000
mutual_authentication() returns 0x8030F010 (The Secure Channel Protocol Implementation passed and the one reported by the card do not match.)
~~~

**Comment by kaoh** [comment]
I see the problem.

Specify: `open_sc -security 3 -keyind 0 -keyver 0 -mac_key 404142434445464748494a4b4c4d4e4f -enc_key 404142434445464748494a4b4c4d4e4f -scpimpl 0x70`. Pay attention to `scpimpl`. See the [manual](https://github.com/kaoh/globalplatform/blob/master/gpshell/src/gpshell.1.md).

Explanation:

The `80CA006600` command is reading the Secure Channel Protocol details and returns SCP03 and as implementation 0x10. The latter means "Pseudo-random card challenge, no R-MAC support, no R-ENCRYPTION support." 
See [here](https://lapo.it/asn1js/#ZkxzSgYHKoZIhvxrAWAMBgoqhkiG_GsCAgIBYwkGByqGSIb8awNkCwYJKoZIhvxrBAMQZQsGCSuFEIZIZAIBA2YMBgorBgEEASoCbgED) the decoded data and pay attention to the 4th OID ending with 4.3.16 ==> SCP03, SCP Impl 16 = 0x10 as hex.
The response from `INIT UPDATE` is `00000604002D0016990E0103707D25077AA35F83232232C32B076554D80000CD9000`. The response is defined according to "Secure Channel Protocol '03' Card Specification v2.2 – Amendment D Version 1.1.1"

~~~
Key diversification data 10 bytes Mandatory
Key information 3 bytes Mandatory
Card challenge 8 bytes Mandatory
Card cryptogram 8 bytes Mandatory
Sequence Counter 3 bytes Conditional
~~~

00000604002D0016990E = Key diversification data
010370 = Key information **<== Error, here we have 0x70 instead of the expected 0x10, i.e. the card is buggy**

**Comment by JakeL2BT** [comment]
To clarify gpshell will ignore the Init_Update response key information values and the open_sc -scpimpl parameter to will use the Get_Data 66 Card recognition data value for the SCP Impl to configure the SC parameters? Are you aware that even with the -scp , -scpimpl set and  get_card_recognition_data, get_secure_channel_protocol_details and get_key_information_templates executed before the open_sc that gpshell still attempts to configure for SCP01?

~~~
get_key_information_templates
Command --> 80CA00E000
Wrapped command --> 80CA00E000
Response <-- E012C00401018810C00402018810C004030188109000
Unwrapped response <-- E012C00401018810C00402018810C004030188109000
14060468 | 14059892 | d68ba8 | %d 
14059948 | 14059948 | d689ac | %d 
1   | 1       | 88   | %d 
14059948 | 14059948 | d689ac | %d 
2   | 1       | 88   | %d 
14059948 | 14059948 | d689ac | %d 
3   | 1       | 88   | %d 
command time: 63 ms
send_apdu_nostop -APDU 80CAFF2100
Command --> 80CAFF2100
Wrapped command --> 80CAFF2100
Response <-- 6A88
Unwrapped response <-- 6A88
send_APDU() returns 0x80206A88 (Success)
command time: 62 ms
get_secure_channel_protocol_details
Command --> 80CA006600
Wrapped command --> 80CA006600
Response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
Unwrapped response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
SCP: 0x03
SCP Impl: 0x10
command time: 172 ms
get_card_recognition_data
Command --> 80CA006600
Wrapped command --> 80CA006600
Response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
Unwrapped response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000
Version: 10010202
SCP: 3 SCP Impl: 10
Card Chip Details: 060a2b060104012a026e0103
command time: 156 ms
open_sc -security 1 -scp 3 -scpimpl 70 -keyind 0 -keyver 0 -mac_key 404142434445464748494a4b4c4d4e4f -enc_key 404142434445464748494a4b4c4d4e4f -kek_key 404142434445464748494a4b4c4d4e4f // Open secure channel
Command --> 8050000008A1709D83B63F507000
Wrapped command --> 8050000008A1709D83B63F507000
Response <-- 00000604002D0016990E010370B3B09BFA845240D2EADA4292DDBAB4BE0000D79000
Unwrapped response <-- 00000604002D0016990E010370B3B09BFA845240D2EADA4292DDBAB4BE0000D79000
mutual_authentication() returns 0x80302000 (The verification of the card cryptogram failed.)
------------------------------------------------------------------------------------------------------
13/10 14:52:35  -GP211_check_R_MAC in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1992 : end status 0, error code(0x0): Success

13/10 14:52:35  -unwrap_command in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1921 : end status 0, error code(0x0): Success

13/10 14:52:35  -OPGP_send_APDU in C:\Users\john\Desktop\globalplatform\globalplatform\src\connection.c at line 276 : end status 0, error code(0x80209000): Success

13/10 14:52:35  -get_data in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 1517 : end status 0, error code(0x0): Success

13/10 14:52:35 GP211_get_card_data: OIDCardRecognitionData: 2A864886FC6B01

13/10 14:52:35 GP211_get_card_data: OIDCardManagementTypeAndVersion: 2A864886FC6B02020201

13/10 14:52:35 GP211_get_card_data: OIDCardIdentificationScheme: 2A864886FC6B03

13/10 14:52:35 GP211_get_card_data: OIDSecureChannelProtocol: 2A864886FC6B040310

13/10 14:52:35 GP211_get_card_data: CardConfigurationDetails: 06092B8510864864020103

13/10 14:52:35 GP211_get_card_data: CardChipDetails: 060A2B060104012A026E0103

13/10 14:52:35  -GP211_get_card_data in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 1728 : end status 0, error code(0x0): Success

13/10 14:52:35 Using Secure Channel Protocol 0x03 with Secure Channel Protocol Impl: 0x10


13/10 14:52:35  -GP211_get_secure_channel_protocol_details in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 1765 : end status 0, error code(0x0): Success

13/10 14:52:35 +GP211_get_card_data in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 1585 : start

13/10 14:52:35 +get_data in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 1496 : start

13/10 14:52:35 +OPGP_send_APDU in C:\Users\john\Desktop\globalplatform\globalplatform\src\connection.c at line 210 : start

13/10 14:52:35 OPGP_send_APDU: Command --> 80CA006600

13/10 14:52:35 +wrap_command in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1485 : start

13/10 14:52:35  -wrap_command in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1715 : end status 0, error code(0x0): Success

13/10 14:52:35 +OPGP_PL_send_APDU in C:\Users\john\Desktop\globalplatform\gppcscconnectionplugin\src\gppcscconnectionplugin.c at line 301 : start

13/10 14:52:35  -OPGP_PL_send_APDU in C:\Users\john\Desktop\globalplatform\gppcscconnectionplugin\src\gppcscconnectionplugin.c at line 679 : end status 0, error code(0x80209000): 9000: Success. No error.

13/10 14:52:35 OPGP_send_APDU: Response <-- 664C734A06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040310650B06092B8510864864020103660C060A2B060104012A026E01039000

13/10 14:52:35 +GP211_check_R_MAC in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1942 : start

13/10 14:52:35  -GP211_check_R_MAC in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1992 : end status 0, error code(0x0): Success

13/10 14:52:35  -unwrap_command in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1921 : end status 0, error code(0x0): Success

13/10 14:52:35  -OPGP_send_APDU in C:\Users\john\Desktop\globalplatform\globalplatform\src\connection.c at line 276 : end status 0, error code(0x80209000): Success

13/10 14:52:35  -get_data in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 1517 : end status 0, error code(0x0): Success

13/10 14:52:35 GP211_get_card_data: OIDCardRecognitionData: 2A864886FC6B01

13/10 14:52:35 GP211_get_card_data: OIDCardManagementTypeAndVersion: 2A864886FC6B02020201

13/10 14:52:35 GP211_get_card_data: OIDCardIdentificationScheme: 2A864886FC6B03

13/10 14:52:35 GP211_get_card_data: OIDSecureChannelProtocol: 2A864886FC6B040310

13/10 14:52:35 GP211_get_card_data: CardConfigurationDetails: 06092B8510864864020103

13/10 14:52:35 GP211_get_card_data: CardChipDetails: 060A2B060104012A026E0103

13/10 14:52:35  -GP211_get_card_data in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 1728 : end status 0, error code(0x0): Success

13/10 14:52:35 +mutual_authentication in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 4199 : start

13/10 14:52:35 +get_random in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 2196 : start

13/10 14:52:35  -get_random in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 2203 : end status 0, error code(0x0): Success

13/10 14:52:35 mutual_authentication: Generated Host Challenge: A1709D83B63F5070

13/10 14:52:35 +OPGP_send_APDU in C:\Users\john\Desktop\globalplatform\globalplatform\src\connection.c at line 210 : start

13/10 14:52:35 OPGP_send_APDU: Command --> 8050000008A1709D83B63F507000

13/10 14:52:35 +wrap_command in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1485 : start

13/10 14:52:35  -wrap_command in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1715 : end status 0, error code(0x0): Success

13/10 14:52:35 +OPGP_PL_send_APDU in C:\Users\john\Desktop\globalplatform\gppcscconnectionplugin\src\gppcscconnectionplugin.c at line 301 : start

13/10 14:52:35  -OPGP_PL_send_APDU in C:\Users\john\Desktop\globalplatform\gppcscconnectionplugin\src\gppcscconnectionplugin.c at line 679 : end status 0, error code(0x80209000): 9000: Success. No error.

13/10 14:52:35 OPGP_send_APDU: Response <-- 00000604002D0016990E010370B3B09BFA845240D2EADA4292DDBAB4BE0000D79000

13/10 14:52:35 +GP211_check_R_MAC in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1942 : start

13/10 14:52:35  -GP211_check_R_MAC in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1992 : end status 0, error code(0x0): Success

13/10 14:52:35  -unwrap_command in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 1921 : end status 0, error code(0x0): Success

13/10 14:52:35  -OPGP_send_APDU in C:\Users\john\Desktop\globalplatform\globalplatform\src\connection.c at line 276 : end status 0, error code(0x80209000): Success

13/10 14:52:35 mutual_authentication: Secure Channel Protocol: 0x01

13/10 14:52:35 mutual_authentication: Secure Channel Protocol Implementation: 0x05

13/10 14:52:35 mutual_authentication: Key Diversification Data: 00000604002D0016990E

13/10 14:52:35 mutual_authentication: Key Information Data: 0103

13/10 14:52:35 mutual_authentication: Card Challenge: 70B3B09BFA845240

13/10 14:52:35 mutual_authentication: Retrieved Card Cryptogram: D2EADA4292DDBAB4

13/10 14:52:35 +create_session_key_SCP01 in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 722 : start

13/10 14:52:35 +calculate_enc_ecb_two_key_triple_des in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 819 : start

13/10 14:52:35  -calculate_enc_ecb_two_key_triple_des in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 861 : end status 0, error code(0x0): Success

13/10 14:52:35  -create_session_key_SCP01 in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 735 : end status 0, error code(0x0): Success

13/10 14:52:35 +create_session_key_SCP01 in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 722 : start

13/10 14:52:35 +calculate_enc_ecb_two_key_triple_des in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 819 : start

13/10 14:52:35  -calculate_enc_ecb_two_key_triple_des in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 861 : end status 0, error code(0x0): Success

13/10 14:52:35  -create_session_key_SCP01 in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 735 : end status 0, error code(0x0): Success

13/10 14:52:35 mutual_authentication: S-ENC Session Key: 93B2D1E3A03EC685AAA1F45CDBDE0F5C

13/10 14:52:35 mutual_authentication: S-MAC Session Key: 93B2D1E3A03EC685AAA1F45CDBDE0F5C

13/10 14:52:35 mutual_authentication: Data Encryption Key: 404142434445464748494A4B4C4D4E4F

13/10 14:52:35 +calculate_card_cryptogram_SCP01 in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 514 : start

13/10 14:52:35 +calculate_MAC in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 944 : start

13/10 14:52:35  -calculate_MAC in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 981 : end status 0, error code(0x0): Success

13/10 14:52:35  -calculate_card_cryptogram_SCP01 in C:\Users\john\Desktop\globalplatform\globalplatform\src\crypto.c at line 524 : end status 0, error code(0x0): Success

13/10 14:52:35 mutual_authentication: Card Cryptogram to compare: 38B7C6E14300029E

13/10 14:52:35  -mutual_authentication in C:\Users\john\Desktop\globalplatform\globalplatform\src\globalplatform.c at line 4599 : end status 1, error code(0x80302000): The verification of the card cryptogram failed.
~~~

**Comment by kaoh** [comment]
GPShell is using either the information from the `GET DATA` command (automatically executed) before or the option passed to `-scp` and `-scpImpl`. The result of `GET DATA` and `INIT UPDATE` must be identical, otherwise the card is doing something wrong. In your case SCP Impl 0x10 is reported, I don't know what is correct, the information from `GET DATA` or `INIT UPDATE`. Please try both. Also do not forget to prefix the SCP Impl with `0x` for hex:

__Wrong:__ `open_sc -security 1 -scp 3 -scpimpl 70`
__Correct:__ `open_sc -security 1 -scp 3 -scpimpl 0x70`

And also try:

__Correct:__ `open_sc -security 1 -scp 3 -scpimpl 0x10`

__NOTE:__ `get_key_information_templates`, `get_extended_card_resources_information` and `get_secure_channel_protocol_details` can only be used outside of a secure channel. See the [manual here](https://github.com/kaoh/globalplatform/blob/master/gpshell/src/gpshell.1.md).

---

Regarding the SCP01 issue: I need more info here, can you please provide the script you are using? This might be some incorrect option parsing then. Is the script starting with `mode_211`, otherwise the newer GlobalPlatform specification is not used, so also no SCP02 and SCP03.

**Comment by JakeL2BT** [comment]
Successfully have an scp03 session to the card. Changed the -scpimpl from 70 to 0x70 and then added the mode_211 as the first line of the script, as it was not included. This appears to have allowed the SCP03 configurations and reflect it in the debug logs. The -scpimpl change by itself did not enable the scp03. 
If the mode_211 is in the script will GPShell v2.0.0 attempt to auto negotiate the SCP03 session? 
Should I assume from earlier comments that it will set the -scpimpl parameter based on the get_data 66 card data response? 
Will 67 Card Capability Information from GPv2.3.1 be considered as a potential input for SCP parameters?

**Comment by kaoh** [comment]
> If the mode_211 is in the script will GPShell v2.0.0 attempt to auto negotiate the SCP03 session?

GPShell will execute a GET DATA command if `scp` and `scpimpl` is not set. It will rely on this information, it would be possible for SCP03 to do also an auto detection during the mutual authentication, the code is using here a generic approach to support SCP02 and in SCP02 getting the `scpiml` is not supported. A code change would be required, but so far the information from the the card data was always consistent, hence this was never needed.

> Should I assume from earlier comments that it will set the -scpimpl parameter based on the get_data 66 card data response?

Yes, but in your case this is wrong, so currently `-scpiml 0x70` is needed.

> Will 67 Card Capability Information from GPv2.3.1 be considered as a potential input for SCP parameters?

If this structure also contains the SCP information, this might be a patch, but adding an auto detection directly in the mutual authentication is the better solution, I will consider this to support also inconsistencies between the reported data in get_data 66 and during the mutual authentication.
